Repository learning-at-home/hivemind, pull requests merged in 2021-06, with the labels that each got.

#284 Remove use of packaging module to avoid installation errors
  requirements.txt
  setup.py
Labels: bug

#291 Fix Codecov integration with Github Actions
  .github/workflows/run-tests.yml
  codecov.yml
Labels: ci

#295 Refactor P2P before DHT integration
  hivemind/p2p/__init__.py
  hivemind/p2p/p2p_daemon.py
  tests/test_p2p_daemon.py
Labels: refactor
