Repository learning-at-home/hivemind, pull requests merged in 2021-07, with the labels that each got.

#288 Update readthedocs with hivemind.optim
  docs/modules/averaging.rst
  docs/modules/client.rst
  docs/modules/index.rst
  docs/modules/optim.rst
  hivemind/optim/adaptive.py
  hivemind/optim/collaborative.py
Labels: documentation

#296 Convert DHT to libp2p backend
  benchmarks/benchmark_averaging.py
  benchmarks/benchmark_dht.py
  examples/albert/README.md
  examples/albert/arguments.py
  examples/albert/run_trainer.py
  examples/albert/run_training_monitor.py
  examples/albert/utils.py
  hivemind/averaging/averager.py
  hivemind/dht/__init__.py
  hivemind/dht/node.py
  hivemind/dht/protocol.py
  hivemind/dht/routing.py
  hivemind/hivemind_cli/run_server.py
  hivemind/moe/server/__init__.py
  hivemind/p2p/__init__.py
  hivemind/p2p/p2p_daemon.py
  hivemind/p2p/p2p_daemon_bindings/control.py
  hivemind/p2p/servicer.py
  hivemind/proto/dht.proto
  hivemind/utils/networking.py
  tests/conftest.py
  tests/test_auth.py
  tests/test_averaging.py
  tests/test_dht.py
  tests/test_dht_crypto.py
  tests/test_dht_experts.py
  tests/test_dht_node.py
  tests/test_dht_schema.py
  tests/test_moe.py
  tests/test_p2p_daemon.py
  tests/test_p2p_daemon_bindings.py
  tests/test_training.py
  tests/test_utils/__init__.py
  tests/test_utils/dht_swarms.py
  tests/test_utils/p2p_daemon.py
Labels: dht

#313 Rename Endpoint to PeerID in DHT
  hivemind/dht/node.py
  hivemind/dht/protocol.py
  hivemind/dht/routing.py
  hivemind/proto/dht.proto
  tests/test_dht_node.py
  tests/test_routing.py
  tests/test_utils/dht_swarms.py
Labels: dht, refactor

#315 Simplify argument parsing, update docs in ALBERT example
  examples/albert/README.md
  examples/albert/arguments.py
  examples/albert/requirements.txt
  examples/albert/run_trainer.py
  examples/albert/run_training_monitor.py
  examples/albert/tokenize_wikitext103.py
Labels: documentation

#339 Refactor naming and serialization for PeerIDs
  benchmarks/benchmark_averaging.py
  hivemind/averaging/allreduce.py
  hivemind/averaging/averager.py
  hivemind/averaging/group_info.py
  hivemind/averaging/key_manager.py
  hivemind/averaging/matchmaking.py
  hivemind/dht/node.py
  hivemind/dht/protocol.py
  hivemind/optim/collaborative.py
  hivemind/p2p/p2p_daemon.py
  hivemind/proto/averaging.proto
  hivemind/proto/dht.proto
  tests/test_allreduce.py
  tests/test_averaging.py
  tests/test_dht.py
  tests/test_dht_node.py
  tests/test_p2p_daemon.py
  tests/test_p2p_servicer.py
  tests/test_utils/dht_swarms.py
Labels: refactor
